### ISSUE TITLE
render tiles issue when using acf in gutenberg editor

### ISSUE THREAD

**Issue by giuscia** [mcguffin/acf-field-openstreetmap#14] opened 2019-06-04 11:03 UTC
https://github.com/mcguffin/acf-field-openstreetmap/blob/d16fd2965661d343d0e3d676a4d7d304ff273654/assets/js/acf-osm-frontend.js#L4316

add 'load' event to solve the issue:
`onOff(window, 'resize load', this._onResize, this);`

**Comment by mcguffin** [comment] 2019-07-01 11:11
Hi,
Thanks for letting me know!
the code you mentioned is part of the leaflet library (3rd party). The plugins source js lives in https://github.com/mcguffin/acf-field-openstreetmap/tree/master/src/js

Anyway, leaflet was to 1.5.1 in the latest release, and I couldn't reproduce your issue. Please feel free to check again and close this issue, if it works.

**Closed as completed** 2019-07-04 16:18 UTC
